[platformio]
default_envs = captain_control_bringup

[env:captain_control_bringup]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    adafruit/Adafruit LED Backpack Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
