[platformio]
default_envs = captain_control_system

[env]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
board_build.filesystem = spiffs
upload_speed = 115200
lib_deps =
    adafruit/Adafruit LED Backpack Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit NeoPixel
    earlephilhower/ESP8266Audio @ ^1.9.7

[env:captain_control_bringup]
extends = env
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCAPTAIN_SERIALFLASH_SPI_HZ=8000000

[env:captain_control_system]
extends = env
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCAPTAIN_SERIALFLASH_SPI_HZ=8000000
    -DCAPTAIN_APP_MODE_TEST=0

[env:captain_control_test]
extends = env
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCAPTAIN_SERIALFLASH_SPI_HZ=8000000
    -DCAPTAIN_APP_MODE_TEST=1
